version: '2'
services:
  cdsdataservice-app:
    image: cdsdataservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://cdsdataservice-mysql:3306/cdsdataservice?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  cdsdataservice-mysql:
    extends:
      file: mysql.yml
      service: cdsdataservice-mysql
